name: opticash
description: Opticash App
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  auto_route: ^7.7.1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.19.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  responsive_framework: ^1.1.0
  rxdart: ^0.27.7
  simple_animations: ^4.2.0

dev_dependencies:
  auto_route_generator: ^7.2.0
  bloc_test: ^9.1.3
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  integration_test:
    sdk: flutter
  intl_utils: ^2.8.3
  json_serializable: ^6.7.1
  mocktail: ^0.3.0

dependency_overrides:
  dio: 5.3.0 # https://github.com/Milad-Akarie/auto_route_library/issues/1005

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    exclude:
      - assets/env/*
    outputs:
      class_name: AppAssets

flutter:
  uses-material-design: true
  
  assets:
   - assets/images/

  fonts:
  - family: Rogerex
    fonts:
      - asset: assets/fonts/Rogerex/RogerexRegular.ttf
        weight: 300
      - asset: assets/fonts/Rogerex/RogerexMedium.ttf
        weight: 400
      - asset: assets/fonts/Rogerex/RogerexBlack.ttf
        weight: 500
      - asset: assets/fonts/Rogerex/RogerexSemiBold.ttf
        weight: 600
      - asset: assets/fonts/Rogerex/RogerexBold.ttf
        weight: 700
      - asset: assets/fonts/Rogerex/RogerexExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Rogerex/RogerexMax.ttf
        weight: 900